title: Sameer Jain
subtitle: Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer, passionate and self-managed, love automating any boring stuff

url: "https://sameer-j.github.io"
# url: "http://localhost:4000" # for local development
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Sameer Jain
author_bio: Hi, I am Sameer, a Software Engineer
author_email: "sameerj.official@gmail.com"
author_location: India
author_website_url: "https://sameer-j.github.io"
typewrite-text: Software Engineer with 5+ years of experience. Currently looking for a job in React and React Native

# Experiences
author_work_experiences:
  - company_name: RSA
    company_logo: RSA_Security_logo2.svg.png
    company_url: https://www.rsa.com/
    designation: Software Senior Engineer
    description: Worked on Netwitness Platform product
    visibility: true
  - company_name: Persistent Systems
    company_logo: Persistent_Systems_Logo.jpg
    company_url: https://www.persistent.com/
    designation: Software Engineer
    description: Worked on major client products
    visibility: true

# Education
author_education_details:
  - college_logo: mit.jpg
    college_name: Manipal Institue of Technology
    college_url: https://manipal.edu/mit.html
    college_degree: Computer Science and Engineering
    description: Master of Technology
    visibility: true
  - college_logo: gec.png
    college_name: Goa College of Engineering
    college_url: http://www.gec.ac.in/
    college_degree: Computer Engineering
    description: Bachelor of Engineering
    visibility: true

# Projects
# author_project_details:
#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: _sameer_j
github_username: sameer-j
linkedin_username: sameer-j

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# collections:
#   products:
#     output: true
#   authors:
#     output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
